/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"github.com/nycu-ucr/gonet/http"

	"github.com/nycu-ucr/gin"
	"go.mongodb.org/mongo-driver/bson"

	"github.com/nycu-ucr/openapi/models"
	"github.com/nycu-ucr/udr/internal/logger"
	"github.com/nycu-ucr/udr/internal/util"
)

func (p *Processor) ModifyPpDataProcedure(c *gin.Context, collName string, ueId string, patchItem []models.PatchItem) {
	var err error
	var origValue, newValue map[string]interface{}
	filter := bson.M{"ueId": ueId}
	if origValue, newValue, err = p.PatchDataToDBAndNotify(collName, ueId, patchItem, filter); err != nil {
		logger.DataRepoLog.Errorf("ModifyPpDataProcedure err: %+v", err)
		pd := util.ProblemDetailsModifyNotAllowed("")
		c.JSON(int(pd.Status), pd)
		return
	}
	PreHandleOnDataChangeNotify(ueId, CurrentResourceUri, patchItem, origValue, newValue)
	c.Status(http.StatusNoContent)
}
