/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"github.com/nycu-ucr/gonet/http"

	"github.com/nycu-ucr/gin"
	"go.mongodb.org/mongo-driver/bson"

	"github.com/nycu-ucr/udr/internal/logger"
	"github.com/nycu-ucr/util/mongoapi"
)

func (p *Processor) QuerySmfRegListProcedure(c *gin.Context, collName string, ueId string) {
	filter := bson.M{"ueId": ueId}
	smfRegList, err := mongoapi.RestfulAPIGetMany(collName, filter, mongoapi.COLLATION_STRENGTH_IGNORE_CASE)
	if err != nil {
		logger.DataRepoLog.Errorf("QuerySmfRegListProcedure err: %+v", err)
		c.JSON(http.StatusOK, nil)
		return
	}
	c.JSON(http.StatusOK, smfRegList)
}
