/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"github.com/nycu-ucr/gonet/http"

	"github.com/nycu-ucr/gin"

	udr_context "github.com/nycu-ucr/udr/internal/context"
	"github.com/nycu-ucr/udr/internal/logger"
	"github.com/nycu-ucr/udr/internal/util"
)

func (p *Processor) RemovesubscriptionDataSubscriptionsProcedure(c *gin.Context, subsId string) {
	udrSelf := udr_context.GetSelf()
	_, ok := udrSelf.SubscriptionDataSubscriptions[subsId]
	if !ok {
		pd := util.ProblemDetailsNotFound("SUBSCRIPTION_NOT_FOUND")
		logger.DataRepoLog.Errorf("RemovesubscriptionDataSubscriptionsProcedure err: %s", pd.Detail)
		c.JSON(int(pd.Status), pd)
		return
	}
	delete(udrSelf.SubscriptionDataSubscriptions, subsId)
	c.Status(http.StatusNoContent)
}
